"""
LTspice log parser module.

Parses .log files generated by LTspice simulations, extracting SPICE .meas values,
statuses, and potential failure indicators.
"""

import re
from pathlib import Path
from typing import Dict, Any, Optional, Union, Tuple


class LTspiceLogParser:
    """Parser for LTspice text .log files."""

    def __init__(self, log_path: Union[str, Path]):
        self.log_path = Path(log_path)
        if not self.log_path.exists():
            raise FileNotFoundError(f"LTspice log file not found: {self.log_path}")

        with open(self.log_path, 'r', encoding='utf-8', errors='ignore') as f:
            self.log_content = f.read()

    def parse_measurements(self) -> Dict[str, Optional[float]]:
        """Extract all .meas variables and values from the log file.

        Returns:
            Dictionary mapping measurement name (lowercased) to float value (or None if failed).
        """
        measurements: Dict[str, Optional[float]] = {}

        # Regular expressions for LTspice measurement formats:
        # Format 1: "tperiod=3.5097826087e-11 FROM ..."
        # Format 2: "freq: 1/Tperiod=28491793124.8"
        # Format 3: "avgpower: AVG(-V(VDD)*I(V1) )=0.141160332486 FROM ..."
        # Format 4: "Measurement "tperiod" FAIL'ed"

        lines = self.log_content.splitlines()
        for line in lines:
            line_str = line.strip()

            # Check for failed measurements
            fail_match = re.match(r'Measurement\s+"([^"]+)"\s+FAIL\'ed', line_str, re.IGNORECASE)
            if fail_match:
                meas_name = fail_match.group(1).lower()
                measurements[meas_name] = None
                continue

            # Check for name: equation=value or name=value
            if '=' in line_str:
                # Handle "name: expr=val ..." or "name=val ..."
                if ':' in line_str and line_str.find(':') < line_str.find('='):
                    name_part, val_part = line_str.split(':', 1)
                    name = name_part.strip().lower()
                else:
                    name_part, val_part = line_str.split('=', 1)
                    name = name_part.strip().lower()

                # Extract float value right after '='
                # Match numbers like 3.5097e-11, -0.141, 10, 1e9, nan
                val_match = re.search(r'=\s*([+-]?\d+(?:\.\d+)?(?:[eE][+-]?\d+)?)', line_str)
                if val_match:
                    try:
                        measurements[name] = float(val_match.group(1))
                    except ValueError:
                        measurements[name] = None
                else:
                    # Check if explicit NaN
                    if 'nan' in val_part.lower():
                        measurements[name] = None

        return measurements

    def check_simulation_health(self) -> Tuple[bool, str]:
        """Check if the simulation completed without severe SPICE solver convergence errors.

        Returns:
            Tuple of (is_healthy, status_message).
        """
        content_lower = self.log_content.lower()

        if "fatal error" in content_lower:
            return False, "SPICE Fatal Error encountered"
        if "singular matrix" in content_lower:
            return False, "Singular matrix error (node floating/shorted)"
        if "analysis failed" in content_lower:
            return False, "Transient analysis failed"
        if "iteration limit reached" in content_lower:
            return False, "Time step too small / iteration limit reached"

        return True, "OK"
